BEGIN;

GRANT USAGE ON SCHEMA legacy_x TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA legacy_x TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA legacy_x TO service_role;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA legacy_x TO service_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA legacy_x GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA legacy_x GRANT USAGE, SELECT ON SEQUENCES TO service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA legacy_x GRANT EXECUTE ON FUNCTIONS TO service_role;

COMMIT;
