-- DEPRECATED — do not execute.
-- Staff authorization now lives exclusively in legacy_x.staff.
-- legacy_x.users is identity-only and must not recreate role or is_staff columns.
-- Use legacy_x_drop_users_staff_fields.sql after deploying the role-free code.
