-- DEPRECATED — superseded by legacy_x_drop_users_staff_fields.sql.
-- The canonical cleanup retires both users.is_staff and users.role only after
-- the role-free backend/frontend revision is deployed.
